# Use root/example as user/password credentials
version: '3.1'

services:
  posgre_db:
    image: postgres
    restart: always
    ports:
      - 3309:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  rabbit:
    container_name: dev_rabbit
    hostname: rabbit
    image: rabbitmq:3.6.6-management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    ports:
      - "5672:5672"
      - "15672:15672"
